name: first work flow
on:
  push

jobs:
    testing:
      name: Testing
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: list
          run: ls -ltr
        - name: display content
          run: cat README.md      


