name: ASCII artwork
on:
  push

jobs:
  ASCCI_job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: list the files
          run: ls -lrt  
        
        - name: Executing shell script
          run: |
              chmod +x ASCII_script.sh
              ./ASCII_script.sh