name: Matrix Configuration
on:
  workflow_dispatch: 
  push:

jobs:
    deploy-on-ubuntu:
      runs-on: ubuntu-latest
      steps:
        - name: Echo docker details
          run: docker info

        - name: Run docker image
          run: docker run hello-world

        
          
    deploy-on-windows:
        runs-on: windows-latest
        steps:
            - name: Echo docker details
              run: docker info

            - name: Run docker image
              run: docker run hello-world
