name: Multi-job 
on:
  push

jobs:
    build-job-1:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: list the files
          run: ls -lrt  
        
        - name: Executing shell script
          run: |
            sudo apt-get install cowsay
            cowsay -f dragon "run for a cover , I am a drgaon " >> dragon.txt

        - name: upload dragon.txt
          uses: actions/upload-artifact@v4
          with:
            name: dragon-file-name
            path: dragon.txt
          
    test-job-1:
        needs: build-job-1
        runs-on: ubuntu-latest
        steps:
        - name: download dragon.txt
          uses: actions/download-artifact@v4
          with:
            name: dragon-file-name

        - name: Display structure of downloaded files
          run: !
            ls -R
            grep -i "dragon" dragon.txt    
            
        # - name: test file exists
        #   run: grep -i "dragon" dragon.txt

    deploy-job-1:
        needs: [test-job-1]
        runs-on: ubuntu-latest
        steps:
        - name: download dragon.txt
          uses: actions/download-artifact@v4
          with:
            name: dragon-file-name

        - name: display
          run: cat dragon.txt
            
        - name: deploy
          run: echo deploying ...  
    