name: "workflow filters & activities"

on:
  push:
    branches:
      - main
    branches-ignore:
      - 'feature/**'
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md  
    branches:
      - main  
  workflow_dispatch:

jobs:
  example-job:  
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Display event name"
        run: echo "The event that triggered this workflow is ${{ github.event_name }}"